
export default [
    {
      path:'',
      redirect:'/home',
      component:()=>import('@/views/Home'),
      meta:{show:true}
    },
    {
      path:'/home',
      name:'home',
      component:()=>import('@/views/Home'),
      meta:{show:true}
    },
    {
      path:'/search/:keyword?',
      name:'search',
      component:()=>import('@/views/Search'),
      meta:{show:true}
    },
    {
      path:'/login',
      name:'login',
      component:()=>import('@/views/Login'),
      meta:{show:false}
  
    },
    {
      path:'/register',
      name:'register',
      component:()=>import('@/views/Register'),
      meta:{show:false}
    },
    {
      path:'/detail/:goodId',
      name:'detail',
      component:()=>import('@/views/Detail'),
      meta:{show:true}
    },
    {
      path:'/addcartsuccess',
      name:'addcartsuccess',
      component:()=>import('@/views/AddCartSuccess'),
      meta:{show:true}
    },
    {
      path:'/shopcart',
      name:'shopcart',
      component:()=>import('@/views/ShopCart'),
      meta:{show:true}
    },
    {
      path:'/trade',
      name:'trade',
      component:()=>import('@/views/Trade'),
      beforeEnter: (to, from, next) => {
        if(from.path=='/shopcart'){
          next()
        }else{
          next(false)
        }
      },
      meta:{show:true}
    },
    {
      path:'/pay',
      name:'pay',
      component:()=>import('@/views/Pay'),
      beforeEnter: (to, from, next) => {
        if(from.path=='/trade'){
          next()
        }else{
          next(false)
        }
      },
      meta:{show:true}
    },
    {
      path:'/paysuccess',
      name:'paysuccess',
      component:()=>import('@/views/PaySuccess'),
      meta:{show:true}
    },
    {
      path:'/center',
      redirect:'/center/myorder',
      name:'center',
      component:()=>import('@/views/Center'),
      children:[
        {
          path:'myorder',
          name:'myorder',
          component:()=>import('@/views/Center/myOrder')
        },
        {
          path:'grouporder',
          name:'grouporder',
          component:()=>import('@/views/Center/groupOrder')
        }
      ],
      meta:{show:true}
    },
  ]